### ISSUE TITLE
RI: graphically display random intercetps

### ISSUE THREAD

**Issue by norcalbiostat** [norcalbiostat/MATH456_notes#12]
Like with a forest plot. With or without the density.

**Comment by roualdes** [comment]
Do you want me to do this by hand?  Or do you have a library in mind?

**Comment by norcalbiostat** [comment]
I was going to use the `forestplot` package but i'm not sure yet if it'll be easy to get the RI estimates and SE's in there. I'll still handle this part. I did find `sjPlot` which makes kickass summary tables

**Comment by norcalbiostat** [comment]
ermegerd!
https://rpubs.com/yoshio/118501

**Comment by norcalbiostat** [comment]
completed.
