### ISSUE TITLE
Review modifications

### ISSUE THREAD

**Issue by norcalbiostat** [norcalbiostat/MATH456_notes#13]
I added sub-chapters, intro, slightly reorganized the chapter to flow more like lecture notes and less like a text. Info was kickass, I really didn't add much at all. 

If you're ok with the modifications, could you please merge this single RMD file into the master branch? I'll be sure to add the new packages to the master branch version of `_common.R` momentarily.

**Comment by roualdes** [comment]
Just merged into master.  I'll let you close this, in case you need to complain that I didn't merge correctly :)
