### ISSUE TITLE
Confusing notation in 13.3

### ISSUE THREAD

**Issue by ghost** [norcalbiostat/MATH456_notes#15]
The statement "Hotelling (1933) showed that the a_{i, j} are solutions to..." is misleading. This can't possibly be what he showed. The a_{i, j} are scalars, they can't be solutions to a matrix equations. In the video you call \textbf{a} a matrix and then say they are eigenvectors, I assume you mean the columns of the matrix are eigenvectors?   

I recommend changing this to Hotelling (1933) showed that the columns of the matrix (a_{i, j}) are solutions to the equation $(\textbf{\Sigma} - \lambda \textbf{I}) \textbf{a} = \textbf{0}$."

**Comment by norcalbiostat** [comment]
resolved
