### ISSUE TITLE
Local datasets disallow compilation

### ISSUE THREAD

**Issue by roualdes** [norcalbiostat/MATH456_notes#7]
The dataset AddHealth_Wave_IV.csv should be stored remotely, somewhere accessible to anyone trying to compile these notes.  Either within this repository, or on a website and appropriately linked.

Are there any other similarly referenced datasets?

**Comment by norcalbiostat** [comment]
argh. of course there are. i meant to fix those and was going to "do it later". but i'll do it now.

**Comment by norcalbiostat** [comment]
resolved. At least all that I can find.
