### ISSUE TITLE
Randon Intercepts Example Development

### ISSUE THREAD

**Issue by roualdes** [norcalbiostat/MATH456_notes#8]
Pushed work-in-progress branch _random_intercepts_.

Changes:
1) Two makefile commands added, `make clean` and `make open`, to clean up extraneous files and open the book in your default browser, respectively.

2) Line 447 of GLM.Rmd now has female instead of gender, since gender doesn't seem to be a variable in the addhealth dataset.

3) Random intercepts examples started.  More verbiage needed.

**Comment by roualdes** [comment]
Pushed penultimate draft of random intercepts chapter.  Please review.

**Comment by norcalbiostat** [comment]
a good clear example. Will need to add 

- Lots of new terminology that'll have to be introduced before this example. 
- how to code lme4 models
- what `broom` is doing (generically)
- an example of how to read summary(lmer) output, and a comment about the lack of p-values.
 - include a forestplot to graphically examine the different RI's. I just googled [this](https://mvuorre.github.io/brmstools/articles/forest-plots/forest-plots.html) which has some good potential 

Should I open an issue for each one so we can split the work without duplicating efforts?

**Comment by roualdes** [comment]
An issue for each sounds good.  If we are dividing and conquering git's solution to that is sub-branches off of this branch.  What say you to that?

**Comment by norcalbiostat** [comment]
I should merge what you've done so far then.
Hopefully I can just take the two files only.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
